app:
  title: Standalon Backstage Plugin
  baseUrl: http://localhost:3000

organization:
  name: joq.dev

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    img-src: ["'self'", 'https:', 'data:']
    upgrade-insecure-requests: false
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE, PATCH, HEAD]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
  cache:
    store: memory

techdocs:
  builder: 'local'

customize:
  features:
    appLiveView:
      showInSidebar: false
    search:
      showInSidebar: false
